-- Create the database if it doesn't exist
--CREATE DATABASE IF NOT EXISTS DEMO;


--CREATE SCHEMA IF NOT EXISTS PUBLIC;


-- Set the database and schema context
USE SCHEMA POC.TELEMETRY;


-- Create the tables
CREATE OR REPLACE TABLE POC.TELEMETRY.TIME_DEMO
(
     TRIPDURATION INTEGER
    ,STARTTIME TIMESTAMP
    ,STOPTIME TIMESTAMP
    ,START_STATION_ID INTEGER
    ,START_STATION_NAME STRING
    ,GENDER INTEGER
);
