# This is a basic workflow to help you get started with Actions

name: snowflake_CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: setup-python@v2.2.1
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x
          
          
        env:
            SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
            SF_USERNAME: ${{ secrets.SF_USERNAME }}
            SF_ROLE: ${{ secrets.SF_ROLE }}
            SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
            SF_DATABASE: ${{ secrets.SF_DATABASE }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          
      - name: Install dependencies
        run: |
          python -m pip install schemachange
      - name: Run SchemaChange
      
        run: |
          echo "GITHUB Workspace :" $GITHUB_WORKSPACE
          schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE
